version: 2.1

jobs:
  python-job:
    docker:
      - image: circleci/python:3.10.1-node-browsers

    working_directory: /tests
    steps:
      - checkout
      - run:
          name: set up venv
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests/ --html-report=./report/report.html
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tests/test_lists.py;
            echo "my artifact files in a dir" > /result/artifacts/artifact-2;
      - store_artifacts:
          path: report.html
          destination: report
      - store_artifacts:
          path: /tests/test_lists.py
          destination: artifact-file

workflows:
  build-and-test:
    jobs:
      - python-job